name: build-ffmpeg-layer
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build layer
        run: cd layer && mkdir ffmpeg-layer && cd ffmpeg-layer
        run: python3 -m venv python && source python/bin/activate
        run: pip install ffmpeg-python
        run: mkdir bin
        run: curl https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz -o ffmpeg.tar.xz
        run: tar -xf ffmpeg.tar.xz --strip-components 1 -C bin
        
      - name: Upload layer
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-layer
          path: |
            layer/ffmpeg-layer/python/lib/*/site-packages/* 
            layer/ffmpeg-layer/bin/ffmpeg
            layer/ffmpeg-layer/bin/readme.txt

      - name: cleanup layer
        run: rm -rf layer/ffmpeg-layer