name: build-ffmpeg-layer
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build layer
        run: |
          mkdir -p layer/ffmpeg-layer && \
          cd layer/ffmpeg-layer && \
          python3 -m venv python && \
          source python/bin/activate && \
          pip install ffmpeg-python && \
          mkdir bin && \
          curl https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz -o ffmpeg.tar.xz && \
          tar -xf ffmpeg.tar.xz --strip-components 1 -C bin
        
      - name: Upload layer
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-layer
          path: |
            layer/ffmpeg-layer/python/lib/*/site-packages/* 
            layer/ffmpeg-layer/bin/ffmpeg
            layer/ffmpeg-layer/bin/readme.txt

      - name: cleanup layer
        run: rm -rf layer/ffmpeg-layer