name: build-ffmpeg-layer
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build layer
        run: cd layer && chmod +x layer.sh && ./layer.sh

      - name: Upload layer
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-layer
          path: |
            layer/ffmpeg-layer/python/lib/*/site-packages/* 
            layer/ffmpeg-layer/bin/ffmpeg
            layer/ffmpeg-layer/bin/readme.txt

      - name: cleanup layer
        run: rm -rf layer/ffmpeg-layer